import type { Metadata } from "next";
import { Montserrat, Lora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

// Define the fonts with the correct variable names
const montserrat = Montserrat({
   variable: "--font-montserrat",
   subsets: ["latin"],
   weight: ["400", "500", "700", "900"], // Add weights as needed
});

const lora = Lora({
   variable: "--font-lora",
   subsets: ["latin"],
   weight: ["400", "500"],
});

export const metadata: Metadata = {
   title: "Medibridge",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${montserrat.variable} ${lora.variable} antialiased`}>
            <Navbar />
            <main>
               {children}
               <Footer></Footer>
            </main>
         </body>
      </html>
   );
}
