import type { Metadata } from "next";
import { Montserrat, Lora } from "next/font/google";
// @ts-expect-error -this is common css file
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { TanstackQueryProvider } from "@/provider/TanstackQueryProvider";

// Define the fonts with the correct variable names
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"], // Add weights as needed
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Medibridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${lora.variable} antialiased`}>
        <TanstackQueryProvider>
          <Navbar />
          <main>
            {children}
            <Footer></Footer>
          </main>
          <ToastContainer />
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
